import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/ui/Header";
import Footer from "@/ui/Footer";
import MainMenu from "@/ui/MainMenu";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-gray-200 relative min-w-full min-h-full flex flex-col flex-1">
      <Header />
      <main className="flex-1 h-full w-full">
        {" "}
        <MainMenu />
        {children}
      </main>
      <Footer />
    </div>
  );
}
