import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/ui/Header";
import Footer from "@/ui/Footer";
import MainMenu from "@/ui/MainMenu";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Расти Добро",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className=" relative w-full h-full min-h-[1100px] max-w-[1100px] flex flex-col items-center p-[10px] flex-1">
      <Header></Header>
      <main className="flex-1 h-full min-h-[1100px] mt-[100px] pb-[250px]  w-full">
        {children}
      </main>
      <img
        src="/background.jpg"
        className="fixed top-0 left-0 w-full object-cover  h-full -z-30"
      />
      <Footer />
    </div>
  );
}
